name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Ruff Lint
        run: uvx ruff check --output-format=github .

      - name: Ruff Format (check)
        run: uvx ruff format . --check

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Run Codespell
        run: |
          uvx codespell \
            --quiet-level=2 \
            --check-filenames \
            --check-hidden \
            --skip "*.po,*.min.js,*.svg,*.png,*.jpg,*.json" \
            --ignore-words-list "smappee,HA,nd"

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # actions/checkout v6.0.0
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # actions/setup-python v5.4.0
        with:
          python-version: "3.12"
  
      - name: Install mypy + deps + stubs
        run: |
          python -m pip install --upgrade pip
          pip install mypy aiohttp voluptuous homeassistant aiomqtt==2.4.0


      - name: Generate aiomqtt stubs
        run: stubgen -m aiomqtt -o typings

      - name: Run mypy
        env:
          MYPYPATH: typings
        run: mypy custom_components/smappee_ev
            

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.12"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
        with:
          languages: python
          queries: security-extended,security-and-quality
          

      - name: Autobuild
        uses: github/codeql-action/autobuild@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
