name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Ruff Lint
        run: uvx ruff check --output-format=github .

      - name: Ruff Format (check)
        run: uvx ruff format . --check

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Run Codespell
        run: |
          uvx codespell \
            --quiet-level=2 \
            --check-filenames \
            --check-hidden \
            --skip "*.po,*.min.js,*.svg,*.png,*.jpg,*.json" \
            --ignore-words-list "smappee,HA,nd"

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # actions/setup-python v5.4.0
        with:
          python-version: "3.12"
  
      - name: Install mypy + deps + stubs
        run: |
          python -m pip install --upgrade pip
          pip install mypy aiohttp voluptuous homeassistant aiomqtt==2.4.0


      - name: Generate aiomqtt stubs
        run: stubgen -m aiomqtt -o typings

      - name: Run mypy
        env:
          MYPYPATH: typings
        run: mypy custom_components/smappee_ev
            

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
        with:
          languages: python
          queries: security-extended,security-and-quality
          

      - name: Autobuild
        uses: github/codeql-action/autobuild@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
